- hosts: webservers
  remote_user: cloud_user
  vars:
    prompted_family: "{{ family }}"
  tasks:
  - name: Prompt "{{ prompted_family }}" Family
    become: yes
    become_user: root
    copy:
      dest: "/home/cloud_user/family.txt"
      content: "{{ prompted_family }} Family"
    when: ansible_facts['os_family'] == "{{ prompted_family }}"
