- hosts: webservers
  remote_user: cloud_user
  tasks:
  - name: Install ProFTPd
    become: yes
    become_user: root
    apt:
      name: proftpd
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"
  - name: Install Apache
    become: yes
    become_user: root
    yum:
      name: httpd
      state: present
    when: ansible_facts['os_family'] == "RedHat"
  - name: Install MySQL
    become: yes
    become_user: root
    apt:
      name: mysql-server
      state: present
    when: ansible_facts['distribution'] == "Debian"
