---
- hosts: webservers
  become: yes
  tasks:
    - name: install_apache
      yum:
        name: httpd
        state: latest
    - name: httpd_service
      service:
        name: httpd
        state: started
        enable: yes
    - name: create_index.html
      file:
        path: /var/www/html/index.html
        state: touch
    - name: add_hello_world
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello, World!"
