- hosts: webservers
  remote_user: cloud_user
  tasks:
  - name: Prompt Debian
    become: yes
    become_user: root
    copy:
      dest: "/home/cloud_user/file.txt"
      content: Debian Family
    when: ansible_facts['os_family'] == "Debian"
  - name: Prompt RedHat
    become: yes
    become_user: root
    copy:
      dest: "/home/cloud_user/file.txt"
      content: RedHat Family
    when: ansible_facts['os_family'] == "RedHat"
